project:
  type: website
  output-dir: docs

website:
  title: "Nikita Gautam STA 9750"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://<GITHUB_NAME>.github.io/STA9750-2024-FALL/"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        menu:
          - text: "Mini Project 01"
            href: mp01.qmd
format:
  html:
    theme: Cosmo
    toc: false
